services:
  server:
    container_name: vistend-app
    image: g8ld/visten-app
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_HACKER_NEWS_API: ${NEXT_PUBLIC_HACKER_NEWS_API}
        NEXT_PUBLIC_HACKER_NEWS_URL: ${NEXT_PUBLIC_HACKER_NEWS_URL}
    environment:
      NODE_ENV: production
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: always
  nginx:
    image: g8ld/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always